import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Scientists Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <iframe style={{width: '100vw', height: '100vh'}} src='/kill-the-king/index.html'></iframe>
    </>
  )
}
